apiVersion: apps/v1
kind: Deployment
metadata:
    name: vprodb
    labels:
        app: vprodb
spec:
    selector:
        matchLabels:
            app: vprodb
    replicas: 1
    template:
        metadata:
            labels:
                app: vprodb
        spec:
            containers:
              - name: vprodb
                image: vprofile/vprofiledb
                ports:
                  - containerPort: 3306
                    name: vprodb-port
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: app-secret
                        key: db-pass
