apiVersion: v1
kind: Pod
metadata:
    name: vprodb
    labels:
        app: vprodb
spec:
    containers:
      - name: vprodb
        image: visualpath/vpromultidb
        ports:
          - containerPort: 3306
            name: vprodb-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "vprodbpass"
