apiVersion: v1
kind: Pod
metadata:
    name: vproapp
    labels:
        app: vproapp
spec:
    containers:
      - name: vproapp
        image: visualpath/vpromultiapp
        ports:
          - containerPort: 8080
            name: vproapp-port
