apiVersion: v1
kind: Service
metadata:
    name: vproapp-service
spec:
    selector:
        app: vproapp
    ports:
      - port: 30001
        targetPort: vproapp-port
        nodePort: 30001
        protocol: TCP
    type: NodePort
